Use lux-styleguidist (#984)
* Use lux-styleguidist
Update vue and vue dependencies to vue3

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

* Remove vue@2 dependencies from tests

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

* upgrades vue-test-utils to a compatible version and removes localVue refereces from the test files

Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>
Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Kevin Reiss <kevinreiss@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>
Co-authored-by: Shaun Ellis <sdellis@users.noreply.github.com>

* Replace instances of InputText with LuxInputText

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>
Co-authored-by: Shaun Ellis <sdellis@users.noreply.github.com>

* In vue 3, we no longer need .$el

* Use the Vue 3 plugin and component loading syntax (#994)

Also, use the esm-bundler version of vue, which resolved a console warning

* Use lux-heading and lux-text-style components from lux (#996)

* These components now have the lux- prefix
* They need to be added to each instance of the vue app

Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>

* Add Rails UJS back to the javascript (#997)

It previously was giving me a console warning when it was included; I guess that's resolved now, and we need it in order to log in to CAS

* Use lux-data-table, rather than data-table (#1005)

* Build and use lux-styleguidist in CI (#1007)

Start by cloning into ~/lux-styleguidist and adding yalc

Try building lux-styleguidist

NPM install first

Add lux-styleguidist to approvals using yalc

Add lux-styleguidist to approvals using yalc

* Fix indentation using yarn lint (#1008)

* Update hyperlink to lux-hyperlink

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Kevin Reiss <kevinreiss@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>

* Update lux to 5.0.0-alpha.12

Co-authored-by: Beck Davis <beck-davis@users.noreply.github.com>
Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>

* Add prefix in Lux Components

Co-authored-by: Beck Davis <beck-davis@users.noreply.github.com>
Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>

* Vue components call lux components with the lux- prefix (#1022)

* Eslint should ignore the Rails/ujs import (#1023)

* Use the LuxInputSelect's focusSelect() method (#1026)

Also, update components to use the lux- prefix

Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>

* Resolve yarn test warnings

* Update eslint ecmaVersion (#1027)

ESlint was unable to parse optional chaining, since it was using 2018 rules.
Also, the line it was complaining about had an unused assignment, let's remove it!

* Fix views/shared/ specs (#1030)

Closes #1011

* Fix views/absence_requests specs (#1031)

Closes #1012

* Fixes #1009 (#1028)

* Fix test failures for spec/views/travel_requests (#1029)

* i1013: address delegate system test failure (#1032)

* Update components with prefixs. Towards #1017 (#1033)

* Update components with prefixs. Towards #1017 (#1034)

* Update components with lux prefix towards #1017 (#1035)

* Update dropdown prefix with lux (#1037)

* Upgrading absence request form for new lux (#1038)

* Makes progress toward i1013
* Installs the latest alpha release of lux-styleguidist, so that the
  datepicker component is registered

* Update components with lux prefix: my_requests_spec, edit.html.erb, new.html.erb (#1039)

* Use lux-tag and lux-input-button (#1041)

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

* Get a little farther in the test before failing (#1044)

The date range is not currently actually being filled in. You can verify this by turning off "headless" mode and running the test with a byebug after line 64. There are two main errors in the console:
    `TypeError: m.includes is not a function`, raised from the updateRangeInput function in lux-styleguidist
    `TypeError: Cannot read properties of undefined`, raised from the toLocaleDateString function in lux-styleguidist
    See https://github.com/pulibrary/lux-styleguidist/issues/107

* Update lux version to 5.0.0-alpha.15 (#1045)

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

* Update selectors in view tests to match new lux components (#1046)

* Update lux to alpha.16 (#1052)

Co-authored-by: Kim Leaman <kelea99@users.noreply.github.com>
Co-authored-by: Beck Davis <beck-davis@users.noreply.github.com>
Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Kevin Reiss <kevinreiss@users.noreply.github.com>
Co-authored-by: Max Kadel <maxkadel@users.noreply.github.com>
Co-authored-by: regineheberlein <regineheberlein@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>

* lux 5.0.0-alpha.17 (#1056)

* Run CI against published lux-styleguidist release (#1057)

* Lux 5.0.0-alpha18 (#1058)

* Mount the vue application to the parent of our top component (#1059)

Vue 3 needs all vue components to be the descendants of
the element that we mount the application to.  In Vue 2,
we could mount to a component element.

This moves the mount point to the lux-library-header's parent
component, <body>, so that Vue can render the header.

See https://v3-migration.vuejs.org/breaking-changes/mount-changes.html

* Listen for inputvaluechange event, rather than the input event (#1061)

The input event has changed in lux-styleguidist, since it
causes problems with the datepicker.

* update lux to 5.0.0-alpha.19 (#1060)

* Update lux to alpha.21 (#1064)

* Fix styles in the help page (#1072)

* lux alpha.22 release (#1073)

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

* Add lux prefix in various components (#1074)

* Update wrapper component with lux prefix (#1075)

* Update alert with lux prefix- fix delegation (#1076)

* Lux prelease alpha.23 (#1077)

* Lux prerelease alpha.25 (#1087)

* Lux 5.0.0-alpha.26 prerelease (#1089)

* Update slot syntax (#1094)

* Upgrade lux to 5.0.0-alpha.27 (#1103)

* Fix test for card-header (#1107)

Closes #1099

* Add lux prefix in help page (#1111)

* Removed hard-coded styles (#1112)

* Removed hard-coded styles

* Fixed missed merge conflict

---------

Co-authored-by: Ryan Laddusaw <rladdusaw@princeton.edu>

* Sending the escape key to close the autocomplete that was blocking buttons (#1113)

Co-authored-by: Ryan Laddusaw <rladdusaw@princeton.edu>

* Update lux to 5.0.0-alpha.28 (#1114)

* Sending tab to clear autocomplete instead of escape (#1115)

* Sending the escape key to close the autocomplete that was blocking buttons

* Changed escape to tab

---------

Co-authored-by: Ryan Laddusaw <rladdusaw@princeton.edu>

* lux release 5.0.0-alpha.29 (#1119)

* Update lux to alpha-5.0.0-30 (#1120)

* Update lux to alpha-5.0.0-31 (#1122)

Fixes luxInputText border #1121
Fixes bug in autocompleteInput

* update lux to 5.0.0-alpha.32 (#1124)

* Update lux to alpha-5.0.0-33 release (#1125)

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

* Lux 5.0.0-beta.2 (#1128)

Mark Absence workflow tests as pending

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Kevin Reiss <kevinreiss@users.noreply.github.com>

* lux-design-system release 5.0.0-beta.3 (#1132)

* Update location_loader_spec Array spec with contain_exactly (#1133)

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>

---------

Co-authored-by: Jane Sandberg <sandbergja@users.noreply.github.com>
Co-authored-by: Shaun Ellis <shaun@sdellis.com>
Co-authored-by: Christina Chortaria <christinach@users.noreply.github.com>
Co-authored-by: Kevin Reiss <kevinreiss@users.noreply.github.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>
Co-authored-by: Shaun Ellis <sdellis@users.noreply.github.com>
Co-authored-by: Jane Sandberg <js7389@princeton.edu>
Co-authored-by: Max Kadel <mkadel@princeton.edu>
Co-authored-by: Beck Davis <beck-davis@users.noreply.github.com>
Co-authored-by: Kim Leaman <kelea99@users.noreply.github.com>
Co-authored-by: Max Kadel <maxkadel@users.noreply.github.com>
Co-authored-by: regineheberlein <regineheberlein@users.noreply.github.com>
Co-authored-by: rladdusaw <rladdusaw@gmail.com>
Co-authored-by: Ryan Laddusaw <rladdusaw@princeton.edu>